### ISSUE TITLE
Update all dev docs to reflect python 3.6 change

### ISSUE THREAD

**Issue by cduvallet** [qiime2/dev-docs#33]
**Improvement Description**
There are still references to Python 3.5 in the dev docs, which should be updated to reflect the fact that QIIME 2 is now using Python 3.6.

**Comments**
I'm happy to do this, though I thought this might be a good beginner-friendly task that someone else could take up as well.

**References**
I found a few in [Publishing a plugin](https://dev.qiime2.org/latest/publishing/), but there may be other places too.

**Comment by lizgehret** [comment]
closing this out since this was completed in 2019. will make an updated issue for python 3.8
