### ISSUE TITLE
Potentially Unused Variables Containing Older Build Versions

### ISSUE THREAD

**Issue by Davrod29** [qiime2/dev-docs#35]
**Description**
There are two variables in the conf.py file which contain old build version values of QIIME 2. If these variables are not used, they should be removed from the file.

**Steps to reproduce the behavior**
- Go to source/conf.py file and see lines 65 and 67.

**Screenshot**

![image](https://user-images.githubusercontent.com/30784905/60137624-4b711b80-975c-11e9-85b2-a824fd2e1de7.png)

**Computation Environment**
- OS:  macOS Mojave
- QIIME 2 Release 2019.4

**Comments**
The priority for this issue is low. Good first issue.

**Comment by Davrod29** [comment]
@thermokarst @ebolyen After looking into this issue, the variables listed in this issue are being used when the build directory is made. I have an outstanding PR related to conf.py. Should I create a new branch to make the changes to the variable values? Or add another commit to the current PR?

**Comment by thermokarst** [comment]
Please create a new branch and a new PR, thanks!
