### ISSUE TITLE
Many quick search links yield 404 errors.

### ISSUE THREAD

**Issue by ChrisKeefe** [qiime2/dev-docs#39]
**Bug Description**
Many but not all links on quick search results pages fail to generate descriptions, and produce `404 Not Found` errors.This could be an issue with nginx's handling of the links, too, I guess. :man_shrugging: 

Based on a little quick poking, pages nested immediately below `dev.qiime2.org/latest` are handled properly. These are all basically table of contents pages, and index.html files. Child pages (content pages) nested farther down fail. 

E.g.
- Success: `dev.qiime2.org/latest/api-reference/index.html?highlight=api`
- Fail: `dev.qiime2.org/latest/api-reference/sdk.html?highlight=api` fails

**Steps to reproduce the behavior**
1. Go to 'dev.qiime2.org'
2. Enter a common search term in the Quick Search bar (e.g. 'API'). Click 'Go'
3. Look at results, click some links

**Expected behavior**
Search results let users click through to actual content.

**Screenshots**
In this screenshot, all links with `...` descriptions fail:
![image](https://user-images.githubusercontent.com/39198770/81881878-289f4f80-9546-11ea-8def-68a00620e0f8.png)

**Computation Environment**
- OS: linuxmint 19.3
- Browser: firefox 74, chromium 81.0.4044.138

**Questions**
1. Is this an issue with the generated links, or with nginx's handling of them?

**Comment by thermokarst** [comment]
It might also just be an issue with the version sphinx used to build - there have been at least one or two search issues in mainline sphinx releases in the last year or so.

Rather than fix this, I think we should just drop the built-in search from the rendered docs. Even when it "works" it produces pretty bad results.

**Comment by thermokarst** [comment]
The 2019.1 docset was built with Sphinx 1.8.3: https://dev.qiime2.org/2019.1/search/?q=api&check_keywords=yes&area=default . All of the search results _appear_ to be working.

The 2020.2 docset was built with Sphinx 2.4.4.

Related (QIIME 2 ecosystem) issues:
- https://github.com/qiime2/docs/issues/446
- https://github.com/qiime2/docs/issues/308
