### ISSUE TITLE
wrong function call in Associating Formats with a Type?

### ISSUE THREAD

**Issue by ChrisKeefe** [qiime2/dev-docs#50]
**Bug Description**
@Hsapers turned up what looks like an oversight in [Associating Formats with a Type](https://dev.qiime2.org/latest/storing-data/formats/#associating-formats-with-a-type), where we show `plugin.register_semantic_types` instead of `plugin.register_semantic_type_to_format`. The latter function is never used on this page of the docs.

Are we correct that this is an error? If so, @Hsapers would be happy to cut a PR fixing the issue.

**Comment by gregcaporaso** [comment]
Moved this over to https://github.com/caporaso-lab/developing-with-qiime2/issues/43.
